/**
 * Generating-org branding resolver.
 *
 * Any Viva-Fire-specific default asset (logo, flame watermark, SMAS/BAFE/etc.
 * accreditation strip) is a CLAIM that belongs to Viva Fire Protection Ltd.
 * It must never render on a document generated by another organisation —
 * accreditations in particular are legal claims of certification.
 *
 * Rule: assets keyed to Viva render ONLY when the current auth user's org is
 * the canonical Viva org. Every other org gets a neutral fallback (its own
 * uploaded logo if it has one, otherwise plain text; no flame; no
 * accreditation strip) until it configures its own branding.
 */
import { supabase } from "@/integrations/supabase/client";

export const VIVA_ORG_ID = "11111111-1111-1111-1111-111111111111";

export type GeneratingOrgBranding = {
  orgId: string | null;
  isViva: boolean;
  name: string | null;
  logoUrl: string | null;
};

let cached: Promise<GeneratingOrgBranding> | null = null;

const NEUTRAL: GeneratingOrgBranding = {
  orgId: null, isViva: false, name: null, logoUrl: null,
};

export function resetGeneratingOrgBrandingCache() { cached = null; }

export function getGeneratingOrgBranding(): Promise<GeneratingOrgBranding> {
  if (cached) return cached;
  cached = (async (): Promise<GeneratingOrgBranding> => {
    try {
      const { data: sess } = await supabase.auth.getUser();
      const uid = sess.user?.id;
      if (!uid) return NEUTRAL;
      const { data: profile } = await supabase
        .from("profiles").select("org_id").eq("user_id", uid).maybeSingle();
      const orgId = (profile as any)?.org_id as string | undefined;
      if (!orgId) return NEUTRAL;
      const { data: org } = await supabase
        .from("organisations").select("id, name, logo_url").eq("id", orgId).maybeSingle();
      const row = org as any;
      return {
        orgId,
        isViva: orgId === VIVA_ORG_ID,
        name: row?.name ?? null,
        logoUrl: (row?.logo_url && String(row.logo_url).trim()) || null,
      };
    } catch {
      return NEUTRAL;
    }
  })();
  return cached;
}

/** Header logo URL to use when the doc has no template/customer logo.
 *  Viva → their brand logo. Other orgs → their uploaded logo or "" (text). */
export async function getGeneratingOrgFallbackLogoUrl(): Promise<string> {
  const g = await getGeneratingOrgBranding();
  if (g.isViva) return "/images/vivafire-logo-new.png";
  return g.logoUrl ?? "";
}

/** Accreditation URLs to use when the customer has no branding of their own.
 *  Viva → their four badges. Other orgs → [] (no strip). */
export async function getGeneratingOrgFallbackAccreditations(): Promise<string[]> {
  const g = await getGeneratingOrgBranding();
  if (g.isViva) return [
    "/accreditation/smas-logo.png",
    "/accreditation/constructionline-logo.png",
    "/accreditation/iso-9001-logo.jpg",
    "/accreditation/bafe-logo.jpeg",
  ];
  return [];
}

/** Watermark image URL for the current generating org. Viva → flame; other → null. */
export async function getGeneratingOrgWatermarkUrl(): Promise<string | null> {
  const g = await getGeneratingOrgBranding();
  return g.isViva ? "/images/viva-watermark.png?v=4" : null;
}
