export default function FireLiabilityPolicy() {
  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <img src="/servexa-logo.png" alt="Servexa" className="h-10 w-10 rounded-xl" />
            <span className="text-xl font-bold">Servexa</span>
          </div>
          <h1 className="text-3xl font-bold mb-2">Fire Safety Liability Disclaimer</h1>
          <p className="text-sm text-muted-foreground">Last updated: {date}</p>
        </div>
        <div className="space-y-6 text-foreground">
          <section>
            <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 mb-6">
              <p className="text-sm font-medium text-destructive">Important Notice</p>
              <p className="text-sm text-muted-foreground mt-1 leading-relaxed">Servexa is a software platform for managing field service operations. It is not a fire safety authority, inspection body, or certification organisation. Nothing in this platform constitutes professional fire safety advice.</p>
            </div>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Platform Role</h2>
            <p className="text-muted-foreground leading-relaxed">Servexa provides tools to help fire protection businesses manage their operations, including job scheduling, compliance record keeping, RAMS documentation, and engineer workflows. The platform facilitates the recording and organisation of fire safety work — it does not verify, certify, or guarantee the quality of that work.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">2. Responsibility of Contractors</h2>
            <p className="text-muted-foreground leading-relaxed">All fire safety work carried out by users of this platform remains the sole professional and legal responsibility of the contractor organisation and their qualified engineers. Users must ensure that: all work complies with applicable UK fire safety legislation; engineers hold appropriate qualifications and accreditations (e.g. BAFE, FIA); installed systems meet relevant British Standards (e.g. BS 5839, BS 5306, BS 9999); compliance certificates and test records are accurate and complete.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">3. Compliance Records</h2>
            <p className="text-muted-foreground leading-relaxed">While Servexa provides tools to store and manage compliance records, the platform does not independently verify the authenticity, accuracy, or legal sufficiency of any document, certificate, or record uploaded or generated by users. The accuracy and completeness of compliance records remains the responsibility of the user.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">4. AI-Generated Content</h2>
            <p className="text-muted-foreground leading-relaxed">Servexa includes AI-powered features that may assist with RAMS generation, risk assessments, and job briefings. AI-generated content must be reviewed, verified, and approved by a competent and qualified person before use. AI outputs are for assistance only and do not constitute professional fire safety advice or legally compliant documentation without human review.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">5. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">To the fullest extent permitted by law, Servexa shall not be liable for any loss, damage, injury, death, regulatory penalty, or legal liability arising from: reliance on platform-generated documentation without professional verification; fire safety failures at premises where work was managed through the platform; inaccurate or incomplete compliance records entered by users; failure to meet statutory fire safety obligations. Our total liability is limited to the fees paid in the 12 months preceding any claim.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">6. Regulatory Compliance</h2>
            <p className="text-muted-foreground leading-relaxed">Users are solely responsible for ensuring their operations comply with: the Regulatory Reform (Fire Safety) Order 2005; the Fire Safety Act 2021; the Building Safety Act 2022; all relevant British Standards for fire detection, suppression, and protection systems; and any other applicable UK and devolved legislation.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold mb-3">7. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">For queries relating to this disclaimer, contact us at: <a href="mailto:privacy@servexaapp.com" className="underline underline-offset-2 hover:text-foreground transition-colors">privacy@servexaapp.com</a></p>
          </section>
        </div>
      </div>
    </div>
  );
}
