create table if not exists public.help_articles (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  route_pattern text,
  title text not null,
  purpose text not null,
  steps jsonb not null default '[]'::jsonb,
  common_problems jsonb not null default '[]'::jsonb,
  related_slugs text[] not null default '{}',
  keywords text[] not null default '{}',
  last_updated timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_help_articles_slug on public.help_articles(slug);
create index if not exists idx_help_articles_route on public.help_articles(route_pattern);
grant select on public.help_articles to authenticated;
grant all on public.help_articles to service_role;
alter table public.help_articles enable row level security;
create policy "Help articles readable by authenticated users" on public.help_articles for select to authenticated using (true);
create policy "Admins manage help articles" on public.help_articles for all to authenticated using (public.has_role(auth.uid(), 'admin')) with check (public.has_role(auth.uid(), 'admin'));
create or replace function public.touch_help_article_updated()
returns trigger language plpgsql security definer set search_path = public as $$
begin new.last_updated := now(); return new; end $$;
drop trigger if exists trg_touch_help_article on public.help_articles;
create trigger trg_touch_help_article before update on public.help_articles for each row execute function public.touch_help_article_updated();

insert into public.help_articles (slug, route_pattern, title, purpose, steps, common_problems, related_slugs, keywords) values
('dashboard','/','Dashboard','Landing page after sign-in. Admins see director overview (revenue, jobs, engineer activity); engineers see only their own jobs for today.',
'[{"heading":"See today''s work","items":["Open the app — the Dashboard loads by default.","Look at Today''s Jobs for jobs scheduled today.","Click any job card to open its detail page."]},{"heading":"Get to other areas","items":["Use the left sidebar to jump to Jobs, Planner, Customers.","Press Cmd+K (Ctrl+K on Windows) for the command palette."]}]'::jsonb,
'[{"problem":"Dashboard looks empty","fix":"You may have no jobs assigned for today. Try Jobs in the sidebar."},{"problem":"I''m an engineer but I see admin content","fix":"Your role is set to admin. Ask an admin to change it in Settings → Team."}]'::jsonb,
array['jobs','planner'],array['home','overview','stats']),
('jobs','/jobs','Jobs','Central list of all jobs. Create, filter, bulk import and open jobs. References use the VFP- prefix.',
'[{"heading":"Create a job","items":["Click the New Job button (top right).","Fill in customer, site, category, priority and description.","Optionally add engineers, scheduled date, sheets and RAMS.","Click Create Job — reference VFP-xxxxx is auto-generated."]},{"heading":"Bulk import","items":["Click Bulk Import.","Upload a CSV/Excel; the wizard maps columns.","Review the preview and confirm."]},{"heading":"Folder import","items":["Click Folder Import to drop a folder of PDFs/PO documents.","AI extracts each PO into a draft job for review."]},{"heading":"Filter and search","items":["Use the search box for reference/customer/description.","Use status/category/engineer chips.","Click More filters for date range and priority."]}]'::jsonb,
'[{"problem":"Wrong category on a job","fix":"Category is immutable — archive it and create a new one."},{"problem":"Reference number skipped","fix":"Normal — a discarded draft can leave a gap."}]'::jsonb,
array['jobs.create','jobs.detail','planner','po-email-intake'],array['work order','ticket','vfp']),
('jobs.create','/jobs','Creating a job','Full walkthrough of the New Job dialog. Every field can be edited later except category.',
'[{"heading":"Open the dialog","items":["From Jobs: click New Job.","From a customer: open the customer, click New Job (pre-fills customer/site).","From the Planner: drag an empty slot on an engineer''s row."]},{"heading":"Fill required fields","items":["Customer (required).","Site (dropdown of that customer''s sites).","Category (immutable — pick carefully).","Priority (high/medium/low).","Description."]},{"heading":"Optional at creation","items":["Assign engineers.","Set scheduled/due date.","Attach job sheets (auto-suggested by category).","Attach RAMS.","Add parts and cost lines."]},{"heading":"After creation","items":["Toast: Job created — Print site sheets? Click to print paper sheets.","Job opens on its detail page."]}]'::jsonb,
'[{"problem":"Site dropdown is empty","fix":"Customer has no sites yet. Add one from the Customer detail page → Sites section."},{"problem":"I picked the wrong category","fix":"Category can''t change. Archive and recreate."}]'::jsonb,
array['jobs','jobs.detail','customers','sites'],array['new job','create','add']),
('jobs.detail','/jobs/:id','Job detail page','Everything about one job: assignments, visits, documents, sheets, parts, messages, sign-off and activity log.',
'[{"heading":"Assign an engineer","items":["Open the Assignments section.","Click Assign Engineer and pick from the list.","Engineer sees the job on their dashboard and in Today''s Visits."]},{"heading":"Print paper sheets","items":["Click Print for site (top of page, printer icon).","Choose templates.","Use Print all or per-template Print/Download."]},{"heading":"Send messages","items":["Open Messages tab.","Type and Send — engineer sees it and gets a notification."]},{"heading":"Complete the job","items":["Engineer fills sheets on-site (or paper sheets are scanned back in).","Customer signs off (Customer Sign-Off button generates a link/QR).","Set status Completed or create an Invoice."]},{"heading":"Upload photos via mobile","items":["Click Upload via Mobile to show a QR code.","Scan on phone to open the upload page for this job."]}]'::jsonb,
'[{"problem":"Sign-off link doesn''t work","fix":"Link expires after 7 days. Regenerate from Customer Sign-Off."},{"problem":"Documents didn''t auto-attach","fix":"Check the customer has Auto-attach on their paperwork and the category has document templates."}]'::jsonb,
array['jobs','jobs.sheets','jobs.print-site-sheets','customers.detail','rams'],array['assignment','visit','sign off']),
('jobs.sheets','/jobs/:id','Job sheets (digital forms)','Structured forms engineers complete on-site. Templates are defined in Industry Templates and attached to jobs.',
'[{"heading":"Attach a sheet","items":["Job → Job Sheets → Add Sheet.","Pick a published template matching the job category.","Choose quantity (e.g. 2 for two pressure tests)."]},{"heading":"Fill a sheet","items":["Engineer opens the job, taps the sheet, fills fields, adds photos, signs.","Auto-save keeps every change safe.","Submit when complete."]},{"heading":"Review a submitted sheet","items":["Admin sees it as Submitted on the job.","Open it and use the Comments panel to leave feedback."]}]'::jsonb,
'[{"problem":"Template not in the list","fix":"Publish the template in Industry Templates and match the job category."},{"problem":"Sheet won''t submit offline","fix":"It''s queued — check Sync Status; it submits when online."}]'::jsonb,
array['industry-templates','jobs.print-site-sheets','jobs.paper-scan'],array['form','template','submission']),
('jobs.print-site-sheets','/jobs/:id','Print site sheets (paper mirror)','Paper A4 print of a job sheet that mirrors the digital template exactly, so engineers can handwrite on site and the office can scan it back in.',
'[{"heading":"From the job page","items":["Open the job.","Click Print for site.","Pick templates and per-template quantity (System 1 of N).","Print all, or per-template Print/Download."]},{"heading":"From job creation","items":["After Create Job the toast has a Print site sheets action — click it to open the dialog immediately."]}]'::jsonb,
'[{"problem":"Header info missing","fix":"Set scheduled date, engineer, customer and site on the job first — the header pulls from these."},{"problem":"Layout differs from digital","fix":"Report it — paper and digital are meant to be 1:1."}]'::jsonb,
array['jobs.detail','jobs.sheets','jobs.paper-scan'],array['print','paper','a4','site sheet']),
('jobs.paper-scan','/paper-scan-queue','Paper scan intake','How handwritten paper sheets come back: office scans them, uploads via Paper Scan Queue, AI extracts fields, admin reviews and files.',
'[{"heading":"Upload a scan","items":["Sidebar → Paper Scan Queue.","Click Upload Scans and add PDF/photo files.","Each file is queued for AI extraction (Azure OCR + template classification)."]},{"heading":"Review and file","items":["Open a queued item — AI-extracted fields appear beside the image.","Correct any missed values (especially inline handwritten notes).","Click File to Job — the sheet becomes a Submitted job sheet on the target job."]}]'::jsonb,
'[{"problem":"Wrong template detected","fix":"Change the template in the review panel. Make sure DRY RISER VISUAL (etc.) is printed on the paper header."},{"problem":"Missed handwritten value","fix":"Edit it before filing. If repeatedly missed, raise a support ticket."}]'::jsonb,
array['paper-scan-queue','jobs.sheets','jobs.print-site-sheets'],array['ocr','scan','handwriting']),
('paper-scan-queue','/paper-scan-queue','Paper Scan Queue','Admin inbox of paper sheets waiting to be reviewed and filed.',
'[{"heading":"Process the queue","items":["Sidebar → Paper Scan Queue.","Items sorted newest first with status badges.","Click an item to review the AI extraction and file to the correct job."]}]'::jsonb,
'[{"problem":"Item stuck in Processing","fix":"Give it a minute for large PDFs. Errors are logged in the item details."}]'::jsonb,
array['jobs.paper-scan'],array['queue','scan','ocr']),
('po-email-intake','/jobs','PO email intake','Forward a customer PO email to your intake address and Servexa creates a draft job automatically. Body-only emails (no attachment) are also supported.',
'[{"heading":"Set up intake","items":["Ask an admin for your organisation''s intake email address (Settings → Advanced).","Add it as a forward rule in your mail client."]},{"heading":"What happens on receipt","items":["Email is logged (from, subject, attachment count).","AI extracts PO number, customer, site and description from the attachment OR the email body.","A draft job is created with status pending_review.","Original .eml is stored as an attachment on the draft."]},{"heading":"Review the draft","items":["Go to Jobs, filter status Pending review.","Open the draft, verify fields, click Approve to convert to a live job."]}]'::jsonb,
'[{"problem":"No PO number detected","fix":"Draft is still created and flagged Needs review — no PO number detected. Enter it manually before approving."},{"problem":"Email didn''t arrive","fix":"Every received email is logged; raise a support ticket if unsure."}]'::jsonb,
array['jobs','jobs.create'],array['purchase order','email','forward','intake']),
('customers','/customers','Customers','Directory of every customer, with their sites, jobs and paperwork.',
'[{"heading":"Add a customer","items":["Click the New Customer button.","Fill in name, address, contact, phone, email.","Save — the customer appears in the list."]},{"heading":"Upload files","items":["Click Upload Files, pick a customer and drop PDFs/images.","Toggle Auto-attach ON per file so it attaches to every new job for that customer."]},{"heading":"Import in bulk","items":["Click Bulk Import for a CSV/Excel of customers.","Click Import Folder to drop a folder that gets AI-parsed into customer records."]}]'::jsonb,
'[{"problem":"Duplicate customer","fix":"Use the merge tool on the customer record (three-dot menu → Merge into)."}]'::jsonb,
array['customers.detail','sites','jobs.create'],array['client','company','account']),
('customers.detail','/customers/:id','Customer detail','Everything about one customer: sites, jobs, paperwork, portal, contacts.',
'[{"heading":"Create a job for this customer","items":["Click New Job on the customer page — customer is pre-filled.","Pick a site from that customer''s sites."]},{"heading":"Add sites","items":["Sites section → Add Site.","Optional hierarchy: region → site → building → zone."]},{"heading":"Manage paperwork","items":["Paperwork section → upload files.","Toggle Auto-attach ON per file so it attaches automatically to future jobs."]},{"heading":"Customer portal","items":["Portal section → Generate portal link.","Link is valid for 7 days; share with the customer."]}]'::jsonb,
'[{"problem":"Auto-attached doc missing on a new job","fix":"Confirm Auto-attach ON for that file. Only files with the toggle enabled attach."}]'::jsonb,
array['customers','sites','jobs.create'],array['portal','paperwork','contacts']),
('sites','/sites','Sites','Physical locations where work happens. Sites belong to customers and can be hierarchical.',
'[{"heading":"Add a site","items":["Click New Site.","Pick parent customer; enter name, address, postcode, W3W (optional).","Optional: choose site type (region/site/building/zone) to nest under a parent."]},{"heading":"Link assets and jobs","items":["From Assets or a Job, pick this site from the site dropdown."]}]'::jsonb,
'[{"problem":"Postcode won''t geocode","fix":"Enter a valid UK postcode. If never works, check the Google Maps API key in Secrets."}]'::jsonb,
array['customers','assets','jobs.create'],array['location','premises','building']),
('assets','/assets','Assets','Equipment on customer sites (extinguishers, dry risers, sprinklers, alarms). Basis for PPM and asset history.',
'[{"heading":"Add an asset","items":["Click New Asset.","Pick site, category, name; add make/model/serial/tag.","Save."]},{"heading":"Bulk import","items":["Click Bulk Import; upload CSV/Excel; the wizard maps columns."]},{"heading":"Auto-population","items":["When a Dry Riser Visual sheet is submitted, the asset register is created/updated automatically.","If outlet count differs, a review flag is raised instead of overwriting."]}]'::jsonb,
'[{"problem":"Asset outlet count changed unexpectedly","fix":"Prevented — the system flags a review. Check the review inbox and confirm."}]'::jsonb,
array['assets.detail','sites','jobs.sheets'],array['equipment','ppm','extinguisher','dry riser']),
('assets.detail','/assets/:id','Asset detail','One asset: details, documents, PPM schedule and service history.',
'[{"heading":"View service history","items":["Open the asset — Service History tab lists every job/sheet touching this asset."]},{"heading":"Attach documents","items":["Documents tab → Upload — certificates, warranties, install docs."]},{"heading":"PPM schedule","items":["PPM tab → Add Schedule; set frequency (default 6-monthly).","Servexa auto-generates the next PPM job on schedule."]}]'::jsonb,
'[{"problem":"PPM jobs not generating","fix":"Check the schedule''s next due date and that customer/site are active."}]'::jsonb,
array['assets','jobs'],array['history','ppm','documents']),
('engineers','/engineers','Engineers','Manage engineer accounts, certifications, documents and page access.',
'[{"heading":"Add an engineer","items":["Click Add Engineer.","Enter name, email, phone; save. An onboarding email is sent."]},{"heading":"Upload documents","items":["Open the engineer → Documents → Choose Files.","Documents with expiry dates trigger 30-day alerts."]},{"heading":"Control page access","items":["Open engineer → Page Access → toggle Jobs, Planner, Reports, etc.","Only ticked pages appear in that engineer''s sidebar."]}]'::jsonb,
'[{"problem":"Engineer didn''t get onboarding email","fix":"Check the email in the record, click Resend onboarding email. Check Suppressed Emails in Settings."}]'::jsonb,
array['settings','my-profile'],array['staff','technician','onboarding']),
('planner','/planner','Planner','Drag-and-drop scheduling grid. Assign jobs to engineers on specific dates.',
'[{"heading":"Schedule a job","items":["Drag a job from the Unscheduled column onto an engineer''s date cell.","Or open a job and add a visit manually."]},{"heading":"Change view","items":["Toggle Weekly / Monthly at the top.","Use the arrows to move week by week."]},{"heading":"AI Scheduler","items":["Click AI Scheduler to auto-suggest visits based on engineer skills, distance and workload.","Review and accept/edit before it commits."]}]'::jsonb,
'[{"problem":"Can''t drop onto an engineer","fix":"They may be on leave that day. Move the job to another engineer or day."}]'::jsonb,
array['jobs','leave','engineers'],array['schedule','calendar','drag','ai scheduler']),
('leave','/leave','Leave calendar','Book and view engineer leave. Bank holidays sync from GOV.UK.',
'[{"heading":"Book leave","items":["Click a date on your row → Book Leave.","Pick start/end and type (annual / sick / other).","Admin approves or denies."]}]'::jsonb,
'[{"problem":"Bank holidays missing","fix":"They sync daily. If missing, ask admin to run sync-bank-holidays."}]'::jsonb,
array['planner','engineers'],array['holiday','pto','absence']),
('defects','/defects','Defects','Faults raised on a job by an engineer. Reviewed and either closed or converted into follow-up jobs.',
'[{"heading":"Log a defect","items":["Job → Defects tab → Add Defect.","Enter fault, severity, photos and asset (if known)."]},{"heading":"Review defects","items":["Admins: sidebar → Defects Review.","Convert to a follow-up job or close as resolved."]}]'::jsonb,
'[{"problem":"Defect count in the sidebar looks wrong","fix":"It updates live from open defects; try a hard refresh if stale."}]'::jsonb,
array['defects.review','jobs.detail'],array['fault','snag','issue']),
('defects.review','/defects/review','Defects Review','Admin inbox to triage every open defect across all jobs.',
'[{"heading":"Work the list","items":["Open Defects Review — items grouped by severity.","Click a defect to see photos, notes and parent job.","Actions: Convert to Follow-up Job, or Mark Resolved."]}]'::jsonb,
'[]'::jsonb,
array['defects','jobs.create'],array['triage','follow up']),
('compliance','/compliance','Compliance','Track certificates and inspection expiry across the business.',
'[{"heading":"Add a record","items":["Click Add Compliance Record.","Pick type (Gas Safe, F-Gas, insurance), attach cert, set expiry date."]},{"heading":"Alerts","items":["30 days before expiry, admin gets an email/notification.","Overdue items appear in red on the list."]}]'::jsonb,
'[]'::jsonb,
array['engineers','settings'],array['certificate','expiry','insurance']),
('audits','/audits','Audits','Score-based site/asset audits using configurable templates.',
'[{"heading":"Run an audit","items":["Click New Audit.","Pick site and template.","Complete each item — score calculates live."]},{"heading":"Templates","items":["Manage templates in Settings → Documents (Audit Templates) or Industry Templates."]}]'::jsonb,
'[]'::jsonb,
array['industry-templates'],array['inspection','score','template']),
('site-surveys','/site-surveys','Site Surveys','Structured pre-work surveys with photos, layouts and hazards.',
'[{"heading":"Start a survey","items":["Click New Survey.","Pick customer and site; fill each section as you walk the site.","Capture photos — up to 10 embed in the PDF grid."]},{"heading":"Export","items":["Click Export PDF on a completed survey."]}]'::jsonb,
'[]'::jsonb,
array['sites','jobs.create'],array['pre visit','survey','photos']),
('quotes','/quotes','Quotes','Create QUO- quotes and send for external approval.',
'[{"heading":"Create a quote","items":["Click New Quote; add line items and totals.","Save — reference is QUO-xxxxx."]},{"heading":"Send for approval","items":["Send for Approval generates a token link the customer opens to accept/reject."]}]'::jsonb,
'[]'::jsonb,
array['invoices','customers'],array['quote','estimate','proposal']),
('invoices','/invoices','Invoices','Create invoices from jobs, sync with Xero, track paid/unpaid.',
'[{"heading":"Create from a job","items":["Open a completed job → Create Invoice.","Line items are pre-filled from parts and time; edit as needed.","Save — invoice appears on the Invoices Kanban."]},{"heading":"Sync with Xero","items":["Settings → Integrations → Connect Xero.","Then click Sync to Xero on an invoice."]}]'::jsonb,
'[{"problem":"Xero sync fails","fix":"Reconnect Xero in Settings → Integrations. Tokens expire; a fresh OAuth run usually fixes it."}]'::jsonb,
array['quotes','jobs.detail'],array['invoice','xero','billing']),
('contracts','/contracts','Service Contracts','PPM contracts spanning multiple sites and services, with renewal tracking.',
'[{"heading":"Create a contract","items":["Click New Contract.","Add customer, sites, services and PPM frequency (default 6-monthly).","Set start/end and renewal date."]}]'::jsonb,
'[]'::jsonb,
array['customers','assets'],array['ppm','recurring','maintenance']),
('parts-library','/parts-library','Parts Library','Catalogue of parts used on jobs, with cost and sell prices.',
'[{"heading":"Add a part","items":["Click New Part.","Fill name, SKU, category, cost price and sell price.","Save — it can be picked from jobs."]},{"heading":"Bulk import parts","items":["Bulk Import accepts CSV/Excel; wizard maps columns."]}]'::jsonb,
'[]'::jsonb,
array['van-stock','jobs.detail'],array['sku','stock','pricing']),
('van-stock','/stock','Van Stock','Per-engineer stock levels. Tracks issues and returns against the Parts Library.',
'[{"heading":"Adjust stock","items":["Open Van Stock → pick engineer.","Use Issue or Return to log transactions."]}]'::jsonb,
'[]'::jsonb,
array['parts-library','engineers'],array['van','stock','inventory']),
('industry-templates','/industry-templates','Industry Templates','Library of job-sheet templates and RAMS you can import into your organisation.',
'[{"heading":"Import a template","items":["Browse the list, open a template preview.","Click Import to my templates.","Publish it so it appears on new jobs."]},{"heading":"Author your own","items":["Click New Template.","Add sections and fields; publish when ready."]}]'::jsonb,
'[]'::jsonb,
array['jobs.sheets','rams'],array['template','industry','forms']),
('rams','/rams/start','RAMS','Risk Assessments and Method Statements — draft with AI, then review as a competent person before approving.',
'[{"heading":"Create RAMS","items":["Sidebar → New RAMS; pick job or generic scope.","AI generates a draft — REVIEW every hazard, control and rating."]},{"heading":"Approve","items":["Admin must sign off before RAMS is used on a job.","AI drafts are NOT legal documents until a competent person approves."]}]'::jsonb,
'[{"problem":"Risk rating looks wrong","fix":"Ratings must be validated by a competent person; edit before approval."}]'::jsonb,
array['industry-templates','jobs.detail'],array['risk','method statement','safety']),
('reports','/reports','Reports','Analytics dashboards: revenue, completion, engineer performance, category mix.',
'[{"heading":"Explore","items":["Open Reports; pick a report card.","Filter by date range at the top."]},{"heading":"Engineer performance","items":["Sidebar → Performance (or Reports → Engineer Performance)."]}]'::jsonb,
'[]'::jsonb,
array['report-downloads'],array['analytics','kpi','dashboard']),
('report-downloads','/report-downloads','Report Downloads','Bulk-download signed PDF/Word job reports across jobs.',
'[{"heading":"Download","items":["Filter by date/customer/engineer.","Tick jobs and click Download Selected."]}]'::jsonb,
'[]'::jsonb,
array['reports','jobs.detail'],array['pdf','word','bulk download']),
('settings','/settings','Settings','Workspace configuration: team, email, documents, integrations, advanced tools.',
'[{"heading":"Navigate","items":["Tabs: Team, Email, Documents, Integrations, Advanced."]},{"heading":"Common tasks","items":["Team → add users, set roles, engineer page access.","Email → branding and templates.","Documents → job sheet templates, categories, engineer signatures.","Integrations → Xero, WhatsApp, Microsoft Graph.","Advanced → Storage migration, API key rotation, Weekly Report test, Help Articles."]}]'::jsonb,
'[]'::jsonb,
array['settings.branding','settings.documents','settings.engineer-signatures','settings.import','settings.storage-migration'],array['configure','admin','workspace']),
('settings.branding','/settings','Email branding','Logo, colours and sender name used on customer emails and PDFs.',
'[{"heading":"Update branding","items":["Settings → Email tab.","Upload logo, set primary colour, accreditations.","Send a preview to your own email to check."]}]'::jsonb,
'[]'::jsonb,
array['settings','settings.documents'],array['logo','colours','email header']),
('settings.documents','/settings','Documents settings','Manage job categories, job-sheet templates, audit templates and category document templates.',
'[{"heading":"Job categories","items":["Settings → Documents → Job Categories: add/edit/reorder.","Categories are immutable on existing jobs; changes affect new jobs only."]},{"heading":"Category document templates","items":["Under Documents: link default documents (e.g. RAMS, permits) per category so they auto-attach to new jobs."]}]'::jsonb,
'[]'::jsonb,
array['settings','industry-templates'],array['templates','categories','documents']),
('settings.engineer-signatures','/settings','Engineer signatures','Manage the reusable engineer signature library used on job PDFs.',
'[{"heading":"Add a signature","items":["Settings → Documents → Engineer Signatures.","Draw/upload signature; saves as base64 on the engineer''s profile as a fallback."]}]'::jsonb,
'[]'::jsonb,
array['engineers','settings.documents'],array['signature','sign off']),
('settings.import','/settings/import','Import Wizard','Guided CSV/Excel import for customers, sites and assets with AI column mapping.',
'[{"heading":"Import data","items":["Settings → Documents → Open Import Wizard.","Pick entity (Customers / Sites / Assets).","Upload file, map columns, review preview, commit."]}]'::jsonb,
'[{"problem":"Column not mapping","fix":"Rename headers to match aliases shown, or map manually in the wizard."}]'::jsonb,
array['customers','sites','assets'],array['import','csv','xlsx']),
('settings.storage-migration','/settings','Storage migration (Stage B back-fill)','Admin-only panel that runs the stage-b storage back-fill: renames legacy objects into org-scoped paths and rewrites DB references, with a rollback log.',
'[{"heading":"Dry run first","items":["Settings → Advanced → Storage migration.","Toggle Dry run, pick a bucket, click Run.","Review counts — nothing is moved."]},{"heading":"Run live","items":["Untick Dry run, pick a bucket, click Run.","Panel shows per-bucket counts and integrity check results."]}]'::jsonb,
'[{"problem":"Job stuck","fix":"Check the storage_backfill_log table; every row has old/new paths and a rollback record."}]'::jsonb,
array['settings'],array['migration','back-fill','storage']),
('whatsapp','/settings','WhatsApp features','Send WhatsApp messages to engineers from a Job page, and receive engineer photo replies that queue into paper scans.',
'[{"heading":"Enable WhatsApp","items":["Settings → Integrations → WhatsApp.","Configure Twilio number and webhook."]},{"heading":"Reply from a job","items":["Job detail page → WhatsApp Reply card.","Pick engineer, type message, Send."]}]'::jsonb,
'[{"problem":"Message not delivered","fix":"Check engineer has a WhatsApp number in their profile and Twilio credentials in Secrets."}]'::jsonb,
array['engineers','jobs.detail'],array['whatsapp','twilio','message']),
('fleet','/fleet','Fleet Vehicles','Track fleet vehicles, MOT/service dates, and daily vehicle checks by engineers.',
'[{"heading":"Add a vehicle","items":["Fleet → Add Vehicle; enter reg, make/model, MOT/service dates."]},{"heading":"Vehicle checks","items":["Engineers do daily checks from the mobile app; results appear on the vehicle record."]}]'::jsonb,
'[]'::jsonb,
array['engineers'],array['vehicle','mot','van']),
('my-profile','/my-profile','My Profile','Your personal details, signature and preferences.',
'[{"heading":"Update details","items":["Sidebar → your avatar → My Profile.","Edit name, phone, signature."]}]'::jsonb,
'[]'::jsonb,
array['settings.engineer-signatures'],array['profile','me','signature']),
('my-timesheet','/my-timesheet','My Timesheet','Personal clock-in/out log and totals.',
'[{"heading":"See your hours","items":["Sidebar → your avatar → My Timesheet.","Weekly totals with clock-in/out times."]}]'::jsonb,
'[]'::jsonb,
array['my-profile'],array['timesheet','hours','clock']),
('sync-status','/sync-status','Sync Status','Offline sync queue: pending writes that will submit once you''re back online.',
'[{"heading":"Check queue","items":["Sidebar → Sync Status.","Pending items listed with age; failures shown in red — tap for retry."]}]'::jsonb,
'[]'::jsonb,
array[]::text[],array['offline','queue','sync']),
('setup','/setup','Setup Guide','Onboarding checklist for a new workspace: add engineers, categories, templates, first customer.',
'[{"heading":"Follow the checklist","items":["Sidebar → Setup guide.","Tick items as you complete them."]}]'::jsonb,
'[]'::jsonb,
array['settings'],array['onboarding','getting started','checklist']),
('install','/install','Install (Mobile App)','Install page shown on mobile so engineers can add Servexa to their home screen (PWA).',
'[{"heading":"iPhone","items":["Open in Safari → Share → Add to Home Screen."]},{"heading":"Android","items":["Open in Chrome → menu → Install App."]}]'::jsonb,
'[]'::jsonb,
array['my-profile'],array['pwa','install','mobile']),
('fire-log','/fire-log/:token','Fire Log (customer)','Customer-facing token page to log fire drills, alarm tests and issues on their sites.',
'[{"heading":"Share the link","items":["Generate the Fire Log token from Compliance or the customer record.","Send the link; customer records entries themselves."]}]'::jsonb,
'[]'::jsonb,
array['compliance','customers.detail'],array['fire log','drill','alarm test']),
('sign-off','/sign-off','Customer sign-off','Token-based page a customer opens to sign off a job on their own device.',
'[{"heading":"Generate a link","items":["Job detail → Customer Sign-Off; generates a link/QR valid for 7 days.","Customer opens, reviews and signs.","Sign-off is stored on the job."]}]'::jsonb,
'[{"problem":"Link expired","fix":"Regenerate from the Customer Sign-Off button — old links stop working."}]'::jsonb,
array['jobs.detail'],array['signature','customer','handover']);
